# OpenAPI v3 Training Exercise

openapi: "3.0.0"
info:
  version: 1.0.0
  title: TaxBlaster API
  description: |
    # Answers: New Object Schema
    
    In this exercise, we'll create a new object-typed schema.  
    The new `/tax_payment/{id}` path item has a GET method with a 
    200 response. The schema of the 200 response body only specifies
    that the value must be an object.
    
    Add the necessary fields to the Schema Object to make it validate
    a message payload like this:
    
    ```
    {
      "paymentID": "P12347",
      "date": "2018-04-10",
      "amount": 2231.89,
      "currency": "USD"
    }    
    ```
    
paths:

  /tax_payment/{id}:
    parameters:
    - name: id
      in: path
      description: Payment ID
      required: true
      schema:
        type: string
    get:
      description: Retrieve a single tax payment.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  paymentID:
                    type: string
                  date:
                    type: string
                    format: date
                  amount:
                    type: number
                  currency:
                    type: string

  /taxpayers:
    get:
      description: Retrieve the entire list of taxpayers.
      parameters:
      - name: minTaxDue
        in: query
        schema:
          type: number
        description: >
          Return only taxpayers with taxDue >= the specified value.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Taxpayers"
        default:
          description: >
            Unexpected error in processing the request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /taxpayers/{id}:
    parameters:
    - description: ID of the individual taxpayer.
      name: id
      in: path
      schema:
        type: string
      required: true
    get:
      description: Retrieve an individual taxpayer.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Taxpayer"
        default:
          description: >
            Unexpected error in processing the request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /tax_filings:
    get:
      description: Retrieve all available tax filings
      parameters:
      - name: status
        in: query
        description: > 
          Return only tax filings with the specified tax filing status.
        required: true
        schema:
          type: string
          enum:
          - Draft
          - Submitted
          - Accepted
          - Audit_Pending        
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaxFilings"
        default:
          description: >
            Unexpected error in processing the request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  
  /tax_filings/{id}:
    parameters:
    - name: id
      in: path
      description: ID of the Tax Filing
      required: true
      schema:
        type: string
    get:
      description: Retrieve an individual tax filing
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaxFiling"

components:
  schemas:
  
    TaxFiling:
      type: object
      required:
        - filingID  
      properties:
        filingID:
          type: string
        taxpayerID:
          type: string
        jurisdiction:
          type: string
        fileDate:
          type: string
          format: date
        isJointFiling:
          type: boolean
        filingStatus:
          $ref: "#/components/schemas/TaxFilingStatus"
          
    TaxFilingStatus:
      type: string
      enum:
      - Draft
      - Submitted
      - Accepted
      - Audit_Pending
          
    TaxFilings:
      type: array
      items:
        $ref: "#/components/schemas/TaxFiling"
  
    Taxpayer:
      type: object
      required:
      - taxpayerID
      properties:
        taxpayerID:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        maritalStatus:
          type: boolean
        taxDue:
          type: number
  
    Taxpayers:
      type: array
      items:
        $ref: "#/components/schemas/Taxpayer"
        
    ErrorResponse:
      description: An error string returned from a bad response.
      type: object
      properties:
        errorMessage:
          type: string
        stackTrace:
          type: string
